name: d365_integration
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  injectable: ^2.5.0
  retrofit: ^4.4.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.6.1
  mockito: ^5.4.1
  retrofit_generator: ^8.1.0
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

